apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "issuer.fullname" . }}
  labels:
    {{- include "issuer.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.email }}
    server: {{ .Values.server }}
    privateKeySecretRef:
      name: {{ include "issuer.fullname" . }}
    solvers:
      {{- toYaml .Values.solvers | nindent 6 }}
